joint_limits:
  joint_1:
    has_velocity_limits: true
    max_velocity: 0.32253
    has_acceleration_limits: true
    max_acceleration: 1.46607
  joint_2:
    has_velocity_limits: true
    max_velocity: 0.31374
    has_acceleration_limits: true
    max_acceleration: 1.46607
  joint_3:
    has_velocity_limits: true
    max_velocity: 0.58056
    has_acceleration_limits: true
    max_acceleration: 2.44346
  joint_4:
    has_velocity_limits: true
    max_velocity: 0.59131
    has_acceleration_limits: true
    max_acceleration: 3.29867
  joint_5:
    has_velocity_limits: true
    max_velocity: 0.59131
    has_acceleration_limits: true
    max_acceleration: 3.29867
  joint_6:
    has_velocity_limits: true
    max_velocity: 0.88746
    has_acceleration_limits: true
    max_acceleration: 4.88692
  joint_gripper:
    has_velocity_limits: true
    max_velocity: 0.04
    has_acceleration_limits: false
    max_acceleration: 0
  joint_gripper_mimic:
    has_velocity_limits: true
    max_velocity: 0.04
    has_acceleration_limits: false
    max_acceleration: 0
