#request
std_msgs/Float32MultiArray input_cloud
pose_estimator_msgs/InputCNN input_voxel
# pose_estimator_msgs/InputCNNArray input_voxel
string topic

---
#response
geometry_msgs/Pose pose
geometry_msgs/TransformStamped trans
float32 stamp
bool success
