mhand:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 125

  gripper_controller:
    type: position_controllers/JointTrajectoryController
    joints:
      - finger_A_joint
      - finger_B_joint
      - finger_C_joint
