meshes:
  - name: ARmarker_cube_1
    base_frame: world
    mesh_pkg: kiq_ros_object_descriptions
    path_from_pkg_to_mesh: ar_cube/meshes/STL/ar_cube_id01
    mesh_name: ARmarker_01.stl
    x: 0.3485
    y: 0.5375
    z: 0.0225
    qx: 0.0
    qy: 0.0
    qw: 0.0
    qz: 1.0
  - name: ARmarker_cube_2
    base_frame: world
    mesh_pkg: kiq_ros_object_descriptions
    path_from_pkg_to_mesh: ar_cube/meshes/STL/ar_cube_id02
    mesh_name: ARmarker_02.stl
    x: 0.3485
    y: 0.1325
    z: 0.0225
    qx: 0.0
    qy: 0.0
    qw: 0.0
    qz: 1.0
  - name: ARmarker_cube_3
    base_frame: world
    mesh_pkg: kiq_ros_object_descriptions
    path_from_pkg_to_mesh: ar_cube/meshes/STL/ar_cube_id03
    mesh_name: ARmarker_03.stl
    x: -0.3485
    y: 0.1325
    z: 0.0225
    qx: 0.0
    qy: 0.0
    qw: 0.0
    qz: 1.0
  - name: ARmarker_cube_4
    base_frame: world
    mesh_pkg: kiq_ros_object_descriptions
    path_from_pkg_to_mesh: ar_cube/meshes/STL/ar_cube_id04
    mesh_name: ARmarker_04.stl
    x: -0.3485
    y: 0.5375
    z: 0.0225
    qx: 0.0
    qy: 0.0
    qw: 0.0
    qz: 1.0