meshes:
  - name: HV6_00
    base_frame: world
    mesh_pkg: bayes_pose
    path_from_pkg_to_mesh: model/meshes/STL
    mesh_name: HV6.stl
    x: 0.508
    y: -0.005
    z: 0.01
    qx: 0.0
    qy: 0.0
    qz: 0.707
    qw: 0.707
