meshes:
  - name: HV6_00
    base_frame: world
    mesh_pkg: bayes_pose
    path_from_pkg_to_mesh: model/meshes/STL
    mesh_name: HV6.stl
    x: 0.52
    y: -0.2
    z: -0.02
    qx: 0.0
    qy: 0.0
    qz: 0.0261769
    qw: 0.9996573
    # rpy[deg] = 0,0,3
