meshes:
  - name: HV6_00
    base_frame: world
    mesh_pkg: bayes_pose
    path_from_pkg_to_mesh: model/meshes/STL
    mesh_name: HV6.stl
    x: 0.55
    y: -0.02
    z: 0.08
    qx: 0.3237444
    qy: 0.2716538
    qz: 0.5825634
    qw: 0.694272
    # rpy[deg] = 50,0,80
