meshes:
  - name: HV6_00
    base_frame: world
    mesh_pkg: bayes_pose
    path_from_pkg_to_mesh: model/meshes/STL
    mesh_name: HV6.stl
    x: 0.45
    y: 0.1
    z: -0.1
    qx: 0.0082654
    qy: 0.0176742
    qz: 0.0260197
    qw: 0.999471
    # rpy[deg] = 1,2,3
