meshes:
  - name: HV6_00
    base_frame: world
    mesh_pkg: bayes_pose
    path_from_pkg_to_mesh: model/meshes/STL
    mesh_name: HV6.stl
    x: 0.48
    y: -0.1
    z: 0.05
    qx: 0.0
    qy: 0.0436194
    qz: 0.0
    qw: 0.9990482
    # rpy[deg] = 0,5,0
