meshes:
  - name: HV6_00
    base_frame: world
    mesh_pkg: bayes_pose
    path_from_pkg_to_mesh: model/meshes/STL
    mesh_name: HV6.stl
    x: 0.6
    y: 0.000
    z: 0.002
    qx: -0.1219954
    qy: 0.0513236
    qz: -0.3843702
    qw: 0.9136425
    # rpy[deg] = 50,0,150
