meshes:
  - name: HV6_00
    base_frame: world
    mesh_pkg: bayes_pose
    path_from_pkg_to_mesh: model/meshes/STL
    mesh_name: HV6.stl
    x: 0.5
    y: 0.02
    z: -0.001
    qx: 0.0272845
    qy: -0.0250016
    qz: 0.0442741
    qw: 0.9983338
    # rpy[deg] = 3,-3,5
