meshes:
  - name: HV7_00
    base_frame: world
    mesh_pkg: bayes_pose
    path_from_pkg_to_mesh: model/meshes/STL
    mesh_name: HV7.stl
    x: 0.6
    y: 0.000
    z: 0.002
    qx: -0.1457738
    qy: 0.4210242
    qz: -0.4677972
    qw: 0.763318
    # rpy[deg] = 150,-100,250
