meshes:
  - name: HV7_00
    base_frame: world
    mesh_pkg: bayes_pose
    path_from_pkg_to_mesh: model/meshes/STL
    mesh_name: HV7.stl
    x: 0.43
    y: -0.08
    z: -0.08
    qx: 0.0178157
    qy: 0.0079557
    qz: -0.0437632
    qw: 0.9988514
    # rpy[deg] = 2,1,-5
