meshes:
  - name: HV7_00
    base_frame: world
    mesh_pkg: bayes_pose
    path_from_pkg_to_mesh: model/meshes/STL
    mesh_name: HV7.stl
    x: 0.55
    y: -0.02
    z: 0.08
    qx: 0.0435131
    qy: 0.0030427
    qz: 0.0696901
    qw: 0.9966146
    # rpy[deg] = 5,0,8
