meshes:
  - name: HV7_00
    base_frame: world
    mesh_pkg: bayes_pose
    path_from_pkg_to_mesh: model/meshes/STL
    mesh_name: HV7.stl
    x: 0.65
    y: 0.05
    z: 0.02
    qx: 0.0436194
    qy: 0.0
    qz: 0.0
    qw: 0.9990482
    # rpy[deg] = 5,0,0
