meshes:
  - name: HV8_00
    base_frame: world
    mesh_pkg: bayes_pose
    path_from_pkg_to_mesh: model/meshes/STL
    mesh_name: N_HV8.stl
    x: 0.508
    y: -0.005
    z: 0.01
    # qx: 0.0
    # qy: 0.0
    # qz: 0.707
    # qw: 0.707
    qx: 0.0
    qy: 0.0
    qz: -0.0442427
    qw: -0.9990208
