meshes:
  - name: HV8_00
    base_frame: world
    mesh_pkg: bayes_pose
    path_from_pkg_to_mesh: model/meshes/STL
    mesh_name: N_HV8.stl
    x: 0.55
    y: -0.02
    z: 0.08
    qx: 0.0882704
    qy: -0.098617
    qz: 0.7385583
    qw: -0.6610709
    # rpy[deg] = 50,0,80
