meshes:
  - name: HV8_00
    base_frame: world
    mesh_pkg: bayes_pose
    path_from_pkg_to_mesh: model/meshes/STL
    mesh_name: N_HV8.stl
    x: 0.45
    y: 0.1
    z: -0.1
    qx: -0.5108982
    qy: 0.6404592
    qz: 0.2415334
    qw: 0.5200544
    # rpy[deg] = 10,20,30
