meshes:
  - name: HV8_00
    base_frame: world
    mesh_pkg: bayes_pose
    path_from_pkg_to_mesh: model/meshes/STL
    mesh_name: N_HV8.stl
    x: 0.43
    y: -0.08
    z: -0.08
    qx: -0.2594517
    qy: 0.7771035
    qz: -0.5485872
    qw: -0.1668744
    # rpy[deg] = 20,10,-50
