meshes:
  - name: HV8_00
    base_frame: world
    mesh_pkg: bayes_pose
    path_from_pkg_to_mesh: model/meshes/STL
    mesh_name: N_HV8.stl
    x: 0.5
    y: 0.02
    z: -0.001
    qx: -0.424286
    qy: 0.5550537
    qz: 0.3427706
    qw: 0.6280168
    # rpy[deg] = 30,-30,50
