meshes:
  - name: HV8_00
    base_frame: world
    mesh_pkg: bayes_pose
    path_from_pkg_to_mesh: model/meshes/STL
    mesh_name: N_HV8.stl
    x: 0.65
    y: 0.05
    z: 0.02
    qx: 0.1110526
    qy: -0.0720021
    qz: 0.5392353
    qw: -0.8316901
    # rpy[deg] = 50,0,-20
