meshes:
  - name: HV8_00
    base_frame: world
    mesh_pkg: bayes_pose
    path_from_pkg_to_mesh: model/meshes/STL
    mesh_name: N_HV8.stl
    x: 0.6
    y: 0.000
    z: 0.002
    qx: -0.2395339
    qy: -0.1070705
    qz: -0.8809612
    qw: 0.3937853
    # rpy[deg] = 0,100,-40
