joints_limit:
  gripper:
    finger_A_joint:
      has_position_limits: true
      min_position: -0.007
      max_position: 0
      has_velocity_limits: true
      max_velocity: 6.159937255
      has_acceleration_limits: false
      has_jerk_limits: false
      has_effort_limits: true
      max_effort: 0.5293
    finger_B_joint:
      has_position_limits: true
      min_position: -0.007
      max_position: 0
      has_velocity_limits: true
      max_velocity: 6.159937255
      has_acceleration_limits: false
      has_jerk_limits: false
      has_effort_limits: true
      max_effort: 0.5293

